	.align 2
DirectSoundWaveData_sc88pro_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88pro_glockenspiel.bin"

	.align 2
DirectSoundWaveData_sc88pro_organ2::
	.incbin "sound/direct_sound_samples/sc88pro_organ2.bin"

	.align 2
DirectSoundWaveData_sc88pro_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fretless_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_slap_bass::
	.incbin "sound/direct_sound_samples/sc88pro_slap_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_synth_bass::
	.incbin "sound/direct_sound_samples/sc88pro_synth_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani::
	.incbin "sound/direct_sound_samples/sc88pro_timpani.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/classical_choir_voice_ahhs.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.align 2
DirectSoundWaveData_unused_guitar_separates_power_chord::
	.incbin "sound/direct_sound_samples/unused_guitar_separates_power_chord.bin"

	.align 2
DirectSoundWaveData_unused_sc88pro_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88pro_unison_slap.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/unknown_snare.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_ohtsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_ohtsuzumi.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_hyoushigi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_hyoushigi.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_kick::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_kick.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_snare::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_tr909_hand_clap::
	.incbin "sound/direct_sound_samples/sc88pro_tr909_hand_clap.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_snare::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_tambourine::
	.incbin "sound/direct_sound_samples/sc88pro_tambourine.bin"

	.align 2
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "sound/direct_sound_samples/trinity_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_cymbal_crash::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_mute_high_conga::
	.incbin "sound/direct_sound_samples/sc88pro_mute_high_conga.bin"

	.align 2
DirectSoundWaveData_sc88pro_open_low_conga::
	.incbin "sound/direct_sound_samples/sc88pro_open_low_conga.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_kick.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/sd90_solo_snare.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/sd90_ambient_tom.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/dance_drums_ride_bell.bin"

	.align 2
DirectSoundWaveData_sd90_cowbell::
	.incbin "sound/direct_sound_samples/sd90_cowbell.bin"

	.align 2
DirectSoundWaveData_unused_heart_of_asia_indian_drum::
	.incbin "sound/direct_sound_samples/unused_heart_of_asia_indian_drum.bin"

	.align 2
DirectSoundWaveData_sd90_open_triangle::
	.incbin "sound/direct_sound_samples/sd90_open_triangle.bin"

	.align 2
DirectSoundWaveData_sc88pro_jingle_bell::
	.incbin "sound/direct_sound_samples/sc88pro_jingle_bell.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_atarigane::
	.incbin "sound/direct_sound_samples/ethnic_flavours_atarigane.bin"

	.align 2
DirectSoundWaveData_sc88pro_taiko::
	.incbin "sound/direct_sound_samples/sc88pro_taiko.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_kotsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_kotsuzumi.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_48::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_48.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_60::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_72::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_84::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_60::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_72::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_84::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_60::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_72::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_84::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_39:: @N.B.: These tuba samples are actually sampled at 36 and 48, then pitched up
	.incbin "sound/direct_sound_samples/sc88pro_tuba_39.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_51::
	.incbin "sound/direct_sound_samples/sc88pro_tuba_51.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_60::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_72::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_flute::
	.incbin "sound/direct_sound_samples/sc88pro_flute.bin"

	.align 2
DirectSoundWaveData_sc88pro_fingered_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fingered_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88pro_timpani_with_snare.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_square_wave::
	.incbin "sound/direct_sound_samples/sc88pro_square_wave.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.align 2
DirectSoundWaveData_wave_54::
	.incbin "sound/direct_sound_samples/wave_54.bin"

	.align 2
DirectSoundWaveData_sc88pro_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88pro_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_wave_56::
	.incbin "sound/direct_sound_samples/wave_56.bin"

	.align 2
DirectSoundWaveData_wave_57::
	.incbin "sound/direct_sound_samples/wave_57.bin"

	.align 2
DirectSoundWaveData_wave_58::
	.incbin "sound/direct_sound_samples/wave_58.bin"

	.align 2
DirectSoundWaveData_sc88pro_wind::
	.incbin "sound/direct_sound_samples/sc88pro_wind.bin"

	.align 2
DirectSoundWaveData_sc88pro_bubbles::
	.incbin "sound/direct_sound_samples/sc88pro_bubbles.bin"

	.align 2
DirectSoundWaveData_wave_61::
	.incbin "sound/direct_sound_samples/wave_61.bin"

	.align 2
DirectSoundWaveData_wave_62::
	.incbin "sound/direct_sound_samples/wave_62.bin"

	.align 2
DirectSoundWaveData_trinity_30303_mega_bass::
	.incbin "sound/direct_sound_samples/trinity_30303_mega_bass.bin"

	.align 2
DirectSoundWaveData_wave_64::
	.incbin "sound/direct_sound_samples/wave_64.bin"

	.align 2
DirectSoundWaveData_wave_65::
	.incbin "sound/direct_sound_samples/wave_65.bin"

	.align 2
DirectSoundWaveData_sc88pro_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88pro_tubular_bell.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/unknown_close_hihat.bin"

	.align 2
DirectSoundWaveData_wave_68::
	.incbin "sound/direct_sound_samples/wave_68.bin"

	.align 2
DirectSoundWaveData_trinity_big_boned::
	.incbin "sound/direct_sound_samples/trinity_big_boned.bin"

	.align 2
DirectSoundWaveData_sc88pro_harp::
	.incbin "sound/direct_sound_samples/sc88pro_harp.bin"

	.align 2
DirectSoundWaveData_sc88pro_xylophone::
	.incbin "sound/direct_sound_samples/sc88pro_xylophone.bin"

	.align 2
DirectSoundWaveData_wave_72::
	.incbin "sound/direct_sound_samples/wave_72.bin"

	.align 2
DirectSoundWaveData_wave_73::
	.incbin "sound/direct_sound_samples/wave_73.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion::
	.incbin "sound/direct_sound_samples/sc88pro_accordion.bin"

	.align 2
DirectSoundWaveData_unused_sc55_tom::
	.incbin "sound/direct_sound_samples/unused_sc55_tom.bin"


	.align 2
Cry_Bulbasaur::
	.incbin "sound/direct_sound_samples/cry_bulbasaur.bin"

	.align 2
Cry_Ivysaur::
	.incbin "sound/direct_sound_samples/cry_ivysaur.bin"

	.align 2
Cry_Venusaur::
	.incbin "sound/direct_sound_samples/cry_venusaur.bin"

	.align 2
Cry_Charmander::
	.incbin "sound/direct_sound_samples/cry_charmander.bin"

	.align 2
Cry_Charmeleon::
	.incbin "sound/direct_sound_samples/cry_charmeleon.bin"

	.align 2
Cry_Charizard::
	.incbin "sound/direct_sound_samples/cry_charizard.bin"

	.align 2
Cry_Squirtle::
	.incbin "sound/direct_sound_samples/cry_squirtle.bin"

	.align 2
Cry_Wartortle::
	.incbin "sound/direct_sound_samples/cry_wartortle.bin"

	.align 2
Cry_Blastoise::
	.incbin "sound/direct_sound_samples/cry_blastoise.bin"

	.align 2
Cry_Caterpie::
	.incbin "sound/direct_sound_samples/cry_caterpie.bin"

	.align 2
Cry_Metapod::
	.incbin "sound/direct_sound_samples/cry_metapod.bin"

	.align 2
Cry_Butterfree::
	.incbin "sound/direct_sound_samples/cry_butterfree.bin"

	.align 2
Cry_Weedle::
	.incbin "sound/direct_sound_samples/cry_weedle.bin"

	.align 2
Cry_Kakuna::
	.incbin "sound/direct_sound_samples/cry_kakuna.bin"

	.align 2
Cry_Beedrill::
	.incbin "sound/direct_sound_samples/cry_beedrill.bin"

	.align 2
Cry_Pidgey::
	.incbin "sound/direct_sound_samples/cry_pidgey.bin"

	.align 2
Cry_Pidgeotto::
	.incbin "sound/direct_sound_samples/cry_pidgeotto.bin"

	.align 2
Cry_Pidgeot::
	.incbin "sound/direct_sound_samples/cry_pidgeot.bin"

	.align 2
Cry_Rattata::
	.incbin "sound/direct_sound_samples/cry_rattata.bin"

	.align 2
Cry_Raticate::
	.incbin "sound/direct_sound_samples/cry_raticate.bin"

	.align 2
Cry_Spearow::
	.incbin "sound/direct_sound_samples/cry_spearow.bin"

	.align 2
Cry_Fearow::
	.incbin "sound/direct_sound_samples/cry_fearow.bin"

	.align 2
Cry_Ekans::
	.incbin "sound/direct_sound_samples/cry_ekans.bin"

	.align 2
Cry_Arbok::
	.incbin "sound/direct_sound_samples/cry_arbok.bin"

	.align 2
Cry_Pikachu::
	.incbin "sound/direct_sound_samples/cry_pikachu.bin"

	.align 2
Cry_Raichu::
	.incbin "sound/direct_sound_samples/cry_raichu.bin"

	.align 2
Cry_Sandshrew::
	.incbin "sound/direct_sound_samples/cry_sandshrew.bin"

	.align 2
Cry_Sandslash::
	.incbin "sound/direct_sound_samples/cry_sandslash.bin"

	.align 2
Cry_NidoranF::
	.incbin "sound/direct_sound_samples/cry_nidoran_f.bin"

	.align 2
Cry_Nidorina::
	.incbin "sound/direct_sound_samples/cry_nidorina.bin"

	.align 2
Cry_Nidoqueen::
	.incbin "sound/direct_sound_samples/cry_nidoqueen.bin"

	.align 2
Cry_NidoranM::
	.incbin "sound/direct_sound_samples/cry_nidoran_m.bin"

	.align 2
Cry_Nidorino::
	.incbin "sound/direct_sound_samples/cry_nidorino.bin"

	.align 2
Cry_Nidoking::
	.incbin "sound/direct_sound_samples/cry_nidoking.bin"

	.align 2
Cry_Clefairy::
	.incbin "sound/direct_sound_samples/cry_clefairy.bin"

	.align 2
Cry_Clefable::
	.incbin "sound/direct_sound_samples/cry_clefable.bin"

	.align 2
Cry_Vulpix::
	.incbin "sound/direct_sound_samples/cry_vulpix.bin"

	.align 2
Cry_Ninetales::
	.incbin "sound/direct_sound_samples/cry_ninetales.bin"

	.align 2
Cry_Jigglypuff::
	.incbin "sound/direct_sound_samples/cry_jigglypuff.bin"

	.align 2
Cry_Wigglytuff::
	.incbin "sound/direct_sound_samples/cry_wigglytuff.bin"

	.align 2
Cry_Zubat::
	.incbin "sound/direct_sound_samples/cry_zubat.bin"

	.align 2
Cry_Golbat::
	.incbin "sound/direct_sound_samples/cry_golbat.bin"

	.align 2
Cry_Oddish::
	.incbin "sound/direct_sound_samples/cry_oddish.bin"

	.align 2
Cry_Gloom::
	.incbin "sound/direct_sound_samples/cry_gloom.bin"

	.align 2
Cry_Vileplume::
	.incbin "sound/direct_sound_samples/cry_vileplume.bin"

	.align 2
Cry_Paras::
	.incbin "sound/direct_sound_samples/cry_paras.bin"

	.align 2
Cry_Parasect::
	.incbin "sound/direct_sound_samples/cry_parasect.bin"

	.align 2
Cry_Venonat::
	.incbin "sound/direct_sound_samples/cry_venonat.bin"

	.align 2
Cry_Venomoth::
	.incbin "sound/direct_sound_samples/cry_venomoth.bin"

	.align 2
Cry_Diglett::
	.incbin "sound/direct_sound_samples/cry_diglett.bin"

	.align 2
Cry_Dugtrio::
	.incbin "sound/direct_sound_samples/cry_dugtrio.bin"

	.align 2
Cry_Meowth::
	.incbin "sound/direct_sound_samples/cry_meowth.bin"

	.align 2
Cry_Persian::
	.incbin "sound/direct_sound_samples/cry_persian.bin"

	.align 2
Cry_Psyduck::
	.incbin "sound/direct_sound_samples/cry_psyduck.bin"

	.align 2
Cry_Golduck::
	.incbin "sound/direct_sound_samples/cry_golduck.bin"

	.align 2
Cry_Mankey::
	.incbin "sound/direct_sound_samples/cry_mankey.bin"

	.align 2
Cry_Primeape::
	.incbin "sound/direct_sound_samples/cry_primeape.bin"

	.align 2
Cry_Growlithe::
	.incbin "sound/direct_sound_samples/cry_growlithe.bin"

	.align 2
Cry_Arcanine::
	.incbin "sound/direct_sound_samples/cry_arcanine.bin"

	.align 2
Cry_Poliwag::
	.incbin "sound/direct_sound_samples/cry_poliwag.bin"

	.align 2
Cry_Poliwhirl::
	.incbin "sound/direct_sound_samples/cry_poliwhirl.bin"

	.align 2
Cry_Poliwrath::
	.incbin "sound/direct_sound_samples/cry_poliwrath.bin"

	.align 2
Cry_Abra::
	.incbin "sound/direct_sound_samples/cry_abra.bin"

	.align 2
Cry_Kadabra::
	.incbin "sound/direct_sound_samples/cry_kadabra.bin"

	.align 2
Cry_Alakazam::
	.incbin "sound/direct_sound_samples/cry_alakazam.bin"

	.align 2
Cry_Machop::
	.incbin "sound/direct_sound_samples/cry_machop.bin"

	.align 2
Cry_Machoke::
	.incbin "sound/direct_sound_samples/cry_machoke.bin"

	.align 2
Cry_Machamp::
	.incbin "sound/direct_sound_samples/cry_machamp.bin"

	.align 2
Cry_Bellsprout::
	.incbin "sound/direct_sound_samples/cry_bellsprout.bin"

	.align 2
Cry_Weepinbell::
	.incbin "sound/direct_sound_samples/cry_weepinbell.bin"

	.align 2
Cry_Victreebel::
	.incbin "sound/direct_sound_samples/cry_victreebel.bin"

	.align 2
Cry_Tentacool::
	.incbin "sound/direct_sound_samples/cry_tentacool.bin"

	.align 2
Cry_Tentacruel::
	.incbin "sound/direct_sound_samples/cry_tentacruel.bin"

	.align 2
Cry_Geodude::
	.incbin "sound/direct_sound_samples/cry_geodude.bin"

	.align 2
Cry_Graveler::
	.incbin "sound/direct_sound_samples/cry_graveler.bin"

	.align 2
Cry_Golem::
	.incbin "sound/direct_sound_samples/cry_golem.bin"

	.align 2
Cry_Ponyta::
	.incbin "sound/direct_sound_samples/cry_ponyta.bin"

	.align 2
Cry_Rapidash::
	.incbin "sound/direct_sound_samples/cry_rapidash.bin"

	.align 2
Cry_Slowpoke::
	.incbin "sound/direct_sound_samples/cry_slowpoke.bin"

	.align 2
Cry_Slowbro::
	.incbin "sound/direct_sound_samples/cry_slowbro.bin"

	.align 2
Cry_Magnemite::
	.incbin "sound/direct_sound_samples/cry_magnemite.bin"

	.align 2
Cry_Magneton::
	.incbin "sound/direct_sound_samples/cry_magneton.bin"

	.align 2
Cry_Farfetchd::
	.incbin "sound/direct_sound_samples/cry_farfetchd.bin"

	.align 2
Cry_Doduo::
	.incbin "sound/direct_sound_samples/cry_doduo.bin"

	.align 2
Cry_Dodrio::
	.incbin "sound/direct_sound_samples/cry_dodrio.bin"

	.align 2
Cry_Seel::
	.incbin "sound/direct_sound_samples/cry_seel.bin"

	.align 2
Cry_Dewgong::
	.incbin "sound/direct_sound_samples/cry_dewgong.bin"

	.align 2
Cry_Grimer::
	.incbin "sound/direct_sound_samples/cry_grimer.bin"

	.align 2
Cry_Muk::
	.incbin "sound/direct_sound_samples/cry_muk.bin"

	.align 2
Cry_Shellder::
	.incbin "sound/direct_sound_samples/cry_shellder.bin"

	.align 2
Cry_Cloyster::
	.incbin "sound/direct_sound_samples/cry_cloyster.bin"

	.align 2
Cry_Gastly::
	.incbin "sound/direct_sound_samples/cry_gastly.bin"

	.align 2
Cry_Haunter::
	.incbin "sound/direct_sound_samples/cry_haunter.bin"

	.align 2
Cry_Gengar::
	.incbin "sound/direct_sound_samples/cry_gengar.bin"

	.align 2
Cry_Onix::
	.incbin "sound/direct_sound_samples/cry_onix.bin"

	.align 2
Cry_Drowzee::
	.incbin "sound/direct_sound_samples/cry_drowzee.bin"

	.align 2
Cry_Hypno::
	.incbin "sound/direct_sound_samples/cry_hypno.bin"

	.align 2
Cry_Krabby::
	.incbin "sound/direct_sound_samples/cry_krabby.bin"

	.align 2
Cry_Kingler::
	.incbin "sound/direct_sound_samples/cry_kingler.bin"

	.align 2
Cry_Voltorb::
	.incbin "sound/direct_sound_samples/cry_voltorb.bin"

	.align 2
Cry_Electrode::
	.incbin "sound/direct_sound_samples/cry_electrode.bin"

	.align 2
Cry_Exeggcute::
	.incbin "sound/direct_sound_samples/cry_exeggcute.bin"

	.align 2
Cry_Exeggutor::
	.incbin "sound/direct_sound_samples/cry_exeggutor.bin"

	.align 2
Cry_Cubone::
	.incbin "sound/direct_sound_samples/cry_cubone.bin"

	.align 2
Cry_Marowak::
	.incbin "sound/direct_sound_samples/cry_marowak.bin"

	.align 2
Cry_Hitmonlee::
	.incbin "sound/direct_sound_samples/cry_hitmonlee.bin"

	.align 2
Cry_Hitmonchan::
	.incbin "sound/direct_sound_samples/cry_hitmonchan.bin"

	.align 2
Cry_Lickitung::
	.incbin "sound/direct_sound_samples/cry_lickitung.bin"

	.align 2
Cry_Koffing::
	.incbin "sound/direct_sound_samples/cry_koffing.bin"

	.align 2
Cry_Weezing::
	.incbin "sound/direct_sound_samples/cry_weezing.bin"

	.align 2
Cry_Rhyhorn::
	.incbin "sound/direct_sound_samples/cry_rhyhorn.bin"

	.align 2
Cry_Rhydon::
	.incbin "sound/direct_sound_samples/cry_rhydon.bin"

	.align 2
Cry_Chansey::
	.incbin "sound/direct_sound_samples/cry_chansey.bin"

	.align 2
Cry_Tangela::
	.incbin "sound/direct_sound_samples/cry_tangela.bin"

	.align 2
Cry_Kangaskhan::
	.incbin "sound/direct_sound_samples/cry_kangaskhan.bin"

	.align 2
Cry_Horsea::
	.incbin "sound/direct_sound_samples/cry_horsea.bin"

	.align 2
Cry_Seadra::
	.incbin "sound/direct_sound_samples/cry_seadra.bin"

	.align 2
Cry_Goldeen::
	.incbin "sound/direct_sound_samples/cry_goldeen.bin"

	.align 2
Cry_Seaking::
	.incbin "sound/direct_sound_samples/cry_seaking.bin"

	.align 2
Cry_Staryu::
	.incbin "sound/direct_sound_samples/cry_staryu.bin"

	.align 2
Cry_Starmie::
	.incbin "sound/direct_sound_samples/cry_starmie.bin"

	.align 2
Cry_MrMime::
	.incbin "sound/direct_sound_samples/cry_mr_mime.bin"

	.align 2
Cry_Scyther::
	.incbin "sound/direct_sound_samples/cry_scyther.bin"

	.align 2
Cry_Jynx::
	.incbin "sound/direct_sound_samples/cry_jynx.bin"

	.align 2
Cry_Electabuzz::
	.incbin "sound/direct_sound_samples/cry_electabuzz.bin"

	.align 2
Cry_Magmar::
	.incbin "sound/direct_sound_samples/cry_magmar.bin"

	.align 2
Cry_Pinsir::
	.incbin "sound/direct_sound_samples/cry_pinsir.bin"

	.align 2
Cry_Tauros::
	.incbin "sound/direct_sound_samples/cry_tauros.bin"

	.align 2
Cry_Magikarp::
	.incbin "sound/direct_sound_samples/cry_magikarp.bin"

	.align 2
Cry_Gyarados::
	.incbin "sound/direct_sound_samples/cry_gyarados.bin"

	.align 2
Cry_Lapras::
	.incbin "sound/direct_sound_samples/cry_lapras.bin"

	.align 2
Cry_Ditto::
	.incbin "sound/direct_sound_samples/cry_ditto.bin"

	.align 2
Cry_Eevee::
	.incbin "sound/direct_sound_samples/cry_eevee.bin"

	.align 2
Cry_Vaporeon::
	.incbin "sound/direct_sound_samples/cry_vaporeon.bin"

	.align 2
Cry_Jolteon::
	.incbin "sound/direct_sound_samples/cry_jolteon.bin"

	.align 2
Cry_Flareon::
	.incbin "sound/direct_sound_samples/cry_flareon.bin"

	.align 2
Cry_Porygon::
	.incbin "sound/direct_sound_samples/cry_porygon.bin"

	.align 2
Cry_Omanyte::
	.incbin "sound/direct_sound_samples/cry_omanyte.bin"

	.align 2
Cry_Omastar::
	.incbin "sound/direct_sound_samples/cry_omastar.bin"

	.align 2
Cry_Kabuto::
	.incbin "sound/direct_sound_samples/cry_kabuto.bin"

	.align 2
Cry_Kabutops::
	.incbin "sound/direct_sound_samples/cry_kabutops.bin"

	.align 2
Cry_Aerodactyl::
	.incbin "sound/direct_sound_samples/cry_aerodactyl.bin"

	.align 2
Cry_Snorlax::
	.incbin "sound/direct_sound_samples/cry_snorlax.bin"

	.align 2
Cry_Articuno::
	.incbin "sound/direct_sound_samples/cry_articuno.bin"

	.align 2
Cry_Zapdos::
	.incbin "sound/direct_sound_samples/cry_zapdos.bin"

	.align 2
Cry_Moltres::
	.incbin "sound/direct_sound_samples/cry_moltres.bin"

	.align 2
Cry_Dratini::
	.incbin "sound/direct_sound_samples/cry_dratini.bin"

	.align 2
Cry_Dragonair::
	.incbin "sound/direct_sound_samples/cry_dragonair.bin"

	.align 2
Cry_Dragonite::
	.incbin "sound/direct_sound_samples/cry_dragonite.bin"

	.align 2
Cry_Mewtwo::
	.incbin "sound/direct_sound_samples/cry_mewtwo.bin"

	.align 2
Cry_Mew::
	.incbin "sound/direct_sound_samples/cry_mew.bin"

	.align 2
Cry_Chikorita::
	.incbin "sound/direct_sound_samples/cry_chikorita.bin"

	.align 2
Cry_Bayleef::
	.incbin "sound/direct_sound_samples/cry_bayleef.bin"

	.align 2
Cry_Meganium::
	.incbin "sound/direct_sound_samples/cry_meganium.bin"

	.align 2
Cry_Cyndaquil::
	.incbin "sound/direct_sound_samples/cry_cyndaquil.bin"

	.align 2
Cry_Quilava::
	.incbin "sound/direct_sound_samples/cry_quilava.bin"

	.align 2
Cry_Typhlosion::
	.incbin "sound/direct_sound_samples/cry_typhlosion.bin"

	.align 2
Cry_Totodile::
	.incbin "sound/direct_sound_samples/cry_totodile.bin"

	.align 2
Cry_Croconaw::
	.incbin "sound/direct_sound_samples/cry_croconaw.bin"

	.align 2
Cry_Feraligatr::
	.incbin "sound/direct_sound_samples/cry_feraligatr.bin"

	.align 2
Cry_Sentret::
	.incbin "sound/direct_sound_samples/cry_sentret.bin"

	.align 2
Cry_Furret::
	.incbin "sound/direct_sound_samples/cry_furret.bin"

	.align 2
Cry_Hoothoot::
	.incbin "sound/direct_sound_samples/cry_hoothoot.bin"

	.align 2
Cry_Noctowl::
	.incbin "sound/direct_sound_samples/cry_noctowl.bin"

	.align 2
Cry_Ledyba::
	.incbin "sound/direct_sound_samples/cry_ledyba.bin"

	.align 2
Cry_Ledian::
	.incbin "sound/direct_sound_samples/cry_ledian.bin"

	.align 2
Cry_Spinarak::
	.incbin "sound/direct_sound_samples/cry_spinarak.bin"

	.align 2
Cry_Ariados::
	.incbin "sound/direct_sound_samples/cry_ariados.bin"

	.align 2
Cry_Crobat::
	.incbin "sound/direct_sound_samples/cry_crobat.bin"

	.align 2
Cry_Chinchou::
	.incbin "sound/direct_sound_samples/cry_chinchou.bin"

	.align 2
Cry_Lanturn::
	.incbin "sound/direct_sound_samples/cry_lanturn.bin"

	.align 2
Cry_Pichu::
	.incbin "sound/direct_sound_samples/cry_pichu.bin"

	.align 2
Cry_Cleffa::
	.incbin "sound/direct_sound_samples/cry_cleffa.bin"

	.align 2
Cry_Igglybuff::
	.incbin "sound/direct_sound_samples/cry_igglybuff.bin"

	.align 2
Cry_Togepi::
	.incbin "sound/direct_sound_samples/cry_togepi.bin"

	.align 2
Cry_Togetic::
	.incbin "sound/direct_sound_samples/cry_togetic.bin"

	.align 2
Cry_Natu::
	.incbin "sound/direct_sound_samples/cry_natu.bin"

	.align 2
Cry_Xatu::
	.incbin "sound/direct_sound_samples/cry_xatu.bin"

	.align 2
Cry_Mareep::
	.incbin "sound/direct_sound_samples/cry_mareep.bin"

	.align 2
Cry_Flaaffy::
	.incbin "sound/direct_sound_samples/cry_flaaffy.bin"

	.align 2
Cry_Ampharos::
	.incbin "sound/direct_sound_samples/cry_ampharos.bin"

	.align 2
Cry_Bellossom::
	.incbin "sound/direct_sound_samples/cry_bellossom.bin"

	.align 2
Cry_Marill::
	.incbin "sound/direct_sound_samples/cry_marill.bin"

	.align 2
Cry_Azumarill::
	.incbin "sound/direct_sound_samples/cry_azumarill.bin"

	.align 2
Cry_Sudowoodo::
	.incbin "sound/direct_sound_samples/cry_sudowoodo.bin"

	.align 2
Cry_Politoed::
	.incbin "sound/direct_sound_samples/cry_politoed.bin"

	.align 2
Cry_Hoppip::
	.incbin "sound/direct_sound_samples/cry_hoppip.bin"

	.align 2
Cry_Skiploom::
	.incbin "sound/direct_sound_samples/cry_skiploom.bin"

	.align 2
Cry_Jumpluff::
	.incbin "sound/direct_sound_samples/cry_jumpluff.bin"

	.align 2
Cry_Aipom::
	.incbin "sound/direct_sound_samples/cry_aipom.bin"

	.align 2
Cry_Sunkern::
	.incbin "sound/direct_sound_samples/cry_sunkern.bin"

	.align 2
Cry_Sunflora::
	.incbin "sound/direct_sound_samples/cry_sunflora.bin"

	.align 2
Cry_Yanma::
	.incbin "sound/direct_sound_samples/cry_yanma.bin"

	.align 2
Cry_Wooper::
	.incbin "sound/direct_sound_samples/cry_wooper.bin"

	.align 2
Cry_Quagsire::
	.incbin "sound/direct_sound_samples/cry_quagsire.bin"

	.align 2
Cry_Espeon::
	.incbin "sound/direct_sound_samples/cry_espeon.bin"

	.align 2
Cry_Umbreon::
	.incbin "sound/direct_sound_samples/cry_umbreon.bin"

	.align 2
Cry_Murkrow::
	.incbin "sound/direct_sound_samples/cry_murkrow.bin"

	.align 2
Cry_Slowking::
	.incbin "sound/direct_sound_samples/cry_slowking.bin"

	.align 2
Cry_Misdreavus::
	.incbin "sound/direct_sound_samples/cry_misdreavus.bin"

	.align 2
Cry_Unown::
	.incbin "sound/direct_sound_samples/cry_unown.bin"

	.align 2
Cry_Wobbuffet::
	.incbin "sound/direct_sound_samples/cry_wobbuffet.bin"

	.align 2
Cry_Girafarig::
	.incbin "sound/direct_sound_samples/cry_girafarig.bin"

	.align 2
Cry_Pineco::
	.incbin "sound/direct_sound_samples/cry_pineco.bin"

	.align 2
Cry_Forretress::
	.incbin "sound/direct_sound_samples/cry_forretress.bin"

	.align 2
Cry_Dunsparce::
	.incbin "sound/direct_sound_samples/cry_dunsparce.bin"

	.align 2
Cry_Gligar::
	.incbin "sound/direct_sound_samples/cry_gligar.bin"

	.align 2
Cry_Steelix::
	.incbin "sound/direct_sound_samples/cry_steelix.bin"

	.align 2
Cry_Snubbull::
	.incbin "sound/direct_sound_samples/cry_snubbull.bin"

	.align 2
Cry_Granbull::
	.incbin "sound/direct_sound_samples/cry_granbull.bin"

	.align 2
Cry_Qwilfish::
	.incbin "sound/direct_sound_samples/cry_qwilfish.bin"

	.align 2
Cry_Scizor::
	.incbin "sound/direct_sound_samples/cry_scizor.bin"

	.align 2
Cry_Shuckle::
	.incbin "sound/direct_sound_samples/cry_shuckle.bin"

	.align 2
Cry_Heracross::
	.incbin "sound/direct_sound_samples/cry_heracross.bin"

	.align 2
Cry_Sneasel::
	.incbin "sound/direct_sound_samples/cry_sneasel.bin"

	.align 2
Cry_Teddiursa::
	.incbin "sound/direct_sound_samples/cry_teddiursa.bin"

	.align 2
Cry_Ursaring::
	.incbin "sound/direct_sound_samples/cry_ursaring.bin"

	.align 2
Cry_Slugma::
	.incbin "sound/direct_sound_samples/cry_slugma.bin"

	.align 2
Cry_Magcargo::
	.incbin "sound/direct_sound_samples/cry_magcargo.bin"

	.align 2
Cry_Swinub::
	.incbin "sound/direct_sound_samples/cry_swinub.bin"

	.align 2
Cry_Piloswine::
	.incbin "sound/direct_sound_samples/cry_piloswine.bin"

	.align 2
Cry_Corsola::
	.incbin "sound/direct_sound_samples/cry_corsola.bin"

	.align 2
Cry_Remoraid::
	.incbin "sound/direct_sound_samples/cry_remoraid.bin"

	.align 2
Cry_Octillery::
	.incbin "sound/direct_sound_samples/cry_octillery.bin"

	.align 2
Cry_Delibird::
	.incbin "sound/direct_sound_samples/cry_delibird.bin"

	.align 2
Cry_Mantine::
	.incbin "sound/direct_sound_samples/cry_mantine.bin"

	.align 2
Cry_Skarmory::
	.incbin "sound/direct_sound_samples/cry_skarmory.bin"

	.align 2
Cry_Houndour::
	.incbin "sound/direct_sound_samples/cry_houndour.bin"

	.align 2
Cry_Houndoom::
	.incbin "sound/direct_sound_samples/cry_houndoom.bin"

	.align 2
Cry_Kingdra::
	.incbin "sound/direct_sound_samples/cry_kingdra.bin"

	.align 2
Cry_Phanpy::
	.incbin "sound/direct_sound_samples/cry_phanpy.bin"

	.align 2
Cry_Donphan::
	.incbin "sound/direct_sound_samples/cry_donphan.bin"

	.align 2
Cry_Porygon2::
	.incbin "sound/direct_sound_samples/cry_porygon2.bin"

	.align 2
Cry_Stantler::
	.incbin "sound/direct_sound_samples/cry_stantler.bin"

	.align 2
Cry_Smeargle::
	.incbin "sound/direct_sound_samples/cry_smeargle.bin"

	.align 2
Cry_Tyrogue::
	.incbin "sound/direct_sound_samples/cry_tyrogue.bin"

	.align 2
Cry_Hitmontop::
	.incbin "sound/direct_sound_samples/cry_hitmontop.bin"

	.align 2
Cry_Smoochum::
	.incbin "sound/direct_sound_samples/cry_smoochum.bin"

	.align 2
Cry_Elekid::
	.incbin "sound/direct_sound_samples/cry_elekid.bin"

	.align 2
Cry_Magby::
	.incbin "sound/direct_sound_samples/cry_magby.bin"

	.align 2
Cry_Miltank::
	.incbin "sound/direct_sound_samples/cry_miltank.bin"

	.align 2
Cry_Blissey::
	.incbin "sound/direct_sound_samples/cry_blissey.bin"

	.align 2
Cry_Raikou::
	.incbin "sound/direct_sound_samples/cry_raikou.bin"

	.align 2
Cry_Entei::
	.incbin "sound/direct_sound_samples/cry_entei.bin"

	.align 2
Cry_Suicune::
	.incbin "sound/direct_sound_samples/cry_suicune.bin"

	.align 2
Cry_Larvitar::
	.incbin "sound/direct_sound_samples/cry_larvitar.bin"

	.align 2
Cry_Pupitar::
	.incbin "sound/direct_sound_samples/cry_pupitar.bin"

	.align 2
Cry_Tyranitar::
	.incbin "sound/direct_sound_samples/cry_tyranitar.bin"

	.align 2
Cry_Lugia::
	.incbin "sound/direct_sound_samples/cry_lugia.bin"

	.align 2
Cry_HoOh::
	.incbin "sound/direct_sound_samples/cry_ho_oh.bin"

	.align 2
Cry_Celebi::
	.incbin "sound/direct_sound_samples/cry_celebi.bin"

	.align 2
Cry_Kecleon::
	.incbin "sound/direct_sound_samples/cry_kecleon.bin"

	.align 2
Cry_Roselia::
	.incbin "sound/direct_sound_samples/cry_roselia.bin"

	.align 2
Cry_Torkoal::
	.incbin "sound/direct_sound_samples/cry_torkoal.bin"

	.align 2
Cry_Electrike::
	.incbin "sound/direct_sound_samples/cry_electrike.bin"

	.align 2
Cry_Manectric::
	.incbin "sound/direct_sound_samples/cry_manectric.bin"

	.align 2
Cry_Duskull::
	.incbin "sound/direct_sound_samples/cry_duskull.bin"

	.align 2
Cry_Latias::
	.incbin "sound/direct_sound_samples/cry_latias.bin"

	.align 2
Cry_Wynaut::
	.incbin "sound/direct_sound_samples/cry_wynaut.bin"

	.align 2
Cry_Seviper::
	.incbin "sound/direct_sound_samples/cry_seviper.bin"

	.align 2
Cry_Sharpedo::
	.incbin "sound/direct_sound_samples/cry_sharpedo.bin"

	.align 2
Cry_Zangoose::
	.incbin "sound/direct_sound_samples/cry_zangoose.bin"

	.align 2
Cry_Azurill::
	.incbin "sound/direct_sound_samples/cry_azurill.bin"

	.align 2
Cry_Swablu::
	.incbin "sound/direct_sound_samples/cry_swablu.bin"

	.align 2
Cry_Altaria::
	.incbin "sound/direct_sound_samples/cry_altaria.bin"

	.align 2
Cry_Unused265::
	.incbin "sound/direct_sound_samples/cry_unused_265.bin"

	.align 2
Cry_Taillow::
	.incbin "sound/direct_sound_samples/cry_taillow.bin"

	.align 2
Cry_Swellow::
	.incbin "sound/direct_sound_samples/cry_swellow.bin"

	.align 2
Cry_Unused268::
	.incbin "sound/direct_sound_samples/cry_unused_268.bin"

	.align 2
Cry_Spinda::
	.incbin "sound/direct_sound_samples/cry_spinda.bin"

	.align 2
Cry_Torchic::
	.incbin "sound/direct_sound_samples/cry_torchic.bin"

	.align 2
Cry_Combusken::
	.incbin "sound/direct_sound_samples/cry_combusken.bin"

	.align 2
Cry_Blaziken::
	.incbin "sound/direct_sound_samples/cry_blaziken.bin"

	.align 2
Cry_Treecko::
	.incbin "sound/direct_sound_samples/cry_treecko.bin"

	.align 2
Cry_Grovyle::
	.incbin "sound/direct_sound_samples/cry_grovyle.bin"

	.align 2
Cry_Sceptile::
	.incbin "sound/direct_sound_samples/cry_sceptile.bin"

	.align 2
Cry_Mudkip::
	.incbin "sound/direct_sound_samples/cry_mudkip.bin"

	.align 2
Cry_Marshtomp::
	.incbin "sound/direct_sound_samples/cry_marshtomp.bin"

	.align 2
Cry_Swampert::
	.incbin "sound/direct_sound_samples/cry_swampert.bin"

	.align 2
Cry_Pelipper::
	.incbin "sound/direct_sound_samples/cry_pelipper.bin"

	.align 2
Cry_Wingull::
	.incbin "sound/direct_sound_samples/cry_wingull.bin"

	.align 2
Cry_Banette::
	.incbin "sound/direct_sound_samples/cry_banette.bin"

	.align 2
Cry_Shuppet::
	.incbin "sound/direct_sound_samples/cry_shuppet.bin"

	.align 2
Cry_Lotad::
	.incbin "sound/direct_sound_samples/cry_lotad.bin"

	.align 2
Cry_Lombre::
	.incbin "sound/direct_sound_samples/cry_lombre.bin"

	.align 2
Cry_Ludicolo::
	.incbin "sound/direct_sound_samples/cry_ludicolo.bin"

	.align 2
Cry_Seedot::
	.incbin "sound/direct_sound_samples/cry_seedot.bin"

	.align 2
Cry_Nuzleaf::
	.incbin "sound/direct_sound_samples/cry_nuzleaf.bin"

	.align 2
Cry_Shiftry::
	.incbin "sound/direct_sound_samples/cry_shiftry.bin"

	.align 2
Cry_Carvanha::
	.incbin "sound/direct_sound_samples/cry_carvanha.bin"

	.align 2
Cry_Wurmple::
	.incbin "sound/direct_sound_samples/cry_wurmple.bin"

	.align 2
Cry_Silcoon::
	.incbin "sound/direct_sound_samples/cry_silcoon.bin"

	.align 2
Cry_Beautifly::
	.incbin "sound/direct_sound_samples/cry_beautifly.bin"

	.align 2
Cry_Cascoon::
	.incbin "sound/direct_sound_samples/cry_cascoon.bin"

	.align 2
Cry_Dustox::
	.incbin "sound/direct_sound_samples/cry_dustox.bin"

	.align 2
Cry_Ralts::
	.incbin "sound/direct_sound_samples/cry_ralts.bin"

	.align 2
Cry_Kirlia::
	.incbin "sound/direct_sound_samples/cry_kirlia.bin"

	.align 2
Cry_Gardevoir::
	.incbin "sound/direct_sound_samples/cry_gardevoir.bin"

	.align 2
Cry_Slakoth::
	.incbin "sound/direct_sound_samples/cry_slakoth.bin"

	.align 2
Cry_Vigoroth::
	.incbin "sound/direct_sound_samples/cry_vigoroth.bin"

	.align 2
Cry_Slaking::
	.incbin "sound/direct_sound_samples/cry_slaking.bin"

	.align 2
Cry_Nincada::
	.incbin "sound/direct_sound_samples/cry_nincada.bin"

	.align 2
Cry_Ninjask::
	.incbin "sound/direct_sound_samples/cry_ninjask.bin"

	.align 2
Cry_Shedinja::
	.incbin "sound/direct_sound_samples/cry_shedinja.bin"

	.align 2
Cry_Makuhita::
	.incbin "sound/direct_sound_samples/cry_makuhita.bin"

	.align 2
Cry_Hariyama::
	.incbin "sound/direct_sound_samples/cry_hariyama.bin"

	.align 2
Cry_Nosepass::
	.incbin "sound/direct_sound_samples/cry_nosepass.bin"

	.align 2
Cry_Glalie::
	.incbin "sound/direct_sound_samples/cry_glalie.bin"

	.align 2
Cry_Plusle::
	.incbin "sound/direct_sound_samples/cry_plusle.bin"

	.align 2
Cry_Minun::
	.incbin "sound/direct_sound_samples/cry_minun.bin"

	.align 2
Cry_Surskit::
	.incbin "sound/direct_sound_samples/cry_surskit.bin"

	.align 2
Cry_Masquerain::
	.incbin "sound/direct_sound_samples/cry_masquerain.bin"

	.align 2
Cry_Skitty::
	.incbin "sound/direct_sound_samples/cry_skitty.bin"

	.align 2
Cry_Delcatty::
	.incbin "sound/direct_sound_samples/cry_delcatty.bin"

	.align 2
Cry_Gulpin::
	.incbin "sound/direct_sound_samples/cry_gulpin.bin"

	.align 2
Cry_Swalot::
	.incbin "sound/direct_sound_samples/cry_swalot.bin"

	.align 2
Cry_Numel::
	.incbin "sound/direct_sound_samples/cry_numel.bin"

	.align 2
Cry_Camerupt::
	.incbin "sound/direct_sound_samples/cry_camerupt.bin"

	.align 2
Cry_Barboach::
	.incbin "sound/direct_sound_samples/cry_barboach.bin"

	.align 2
Cry_Whiscash::
	.incbin "sound/direct_sound_samples/cry_whiscash.bin"

	.align 2
Cry_Corphish::
	.incbin "sound/direct_sound_samples/cry_corphish.bin"

	.align 2
Cry_Crawdaunt::
	.incbin "sound/direct_sound_samples/cry_crawdaunt.bin"

	.align 2
Cry_Spoink::
	.incbin "sound/direct_sound_samples/cry_spoink.bin"

	.align 2
Cry_Grumpig::
	.incbin "sound/direct_sound_samples/cry_grumpig.bin"

	.align 2
Cry_Trapinch::
	.incbin "sound/direct_sound_samples/cry_trapinch.bin"

	.align 2
Cry_Vibrava::
	.incbin "sound/direct_sound_samples/cry_vibrava.bin"

	.align 2
Cry_Flygon::
	.incbin "sound/direct_sound_samples/cry_flygon.bin"

	.align 2
Cry_Cacnea::
	.incbin "sound/direct_sound_samples/cry_cacnea.bin"

	.align 2
Cry_Cacturne::
	.incbin "sound/direct_sound_samples/cry_cacturne.bin"

	.align 2
Cry_Baltoy::
	.incbin "sound/direct_sound_samples/cry_baltoy.bin"

	.align 2
Cry_Claydol::
	.incbin "sound/direct_sound_samples/cry_claydol.bin"

	.align 2
Cry_Lunatone::
	.incbin "sound/direct_sound_samples/cry_lunatone.bin"

	.align 2
Cry_Solrock::
	.incbin "sound/direct_sound_samples/cry_solrock.bin"

	.align 2
Cry_Feebas::
	.incbin "sound/direct_sound_samples/cry_feebas.bin"

	.align 2
Cry_Milotic::
	.incbin "sound/direct_sound_samples/cry_milotic.bin"

	.align 2
Cry_Absol::
	.incbin "sound/direct_sound_samples/cry_absol.bin"

	.align 2
Cry_Meditite::
	.incbin "sound/direct_sound_samples/cry_meditite.bin"

	.align 2
Cry_Medicham::
	.incbin "sound/direct_sound_samples/cry_medicham.bin"

	.align 2
Cry_Spheal::
	.incbin "sound/direct_sound_samples/cry_spheal.bin"

	.align 2
Cry_Sealeo::
	.incbin "sound/direct_sound_samples/cry_sealeo.bin"

	.align 2
Cry_Walrein::
	.incbin "sound/direct_sound_samples/cry_walrein.bin"

	.align 2
Cry_Clamperl::
	.incbin "sound/direct_sound_samples/cry_clamperl.bin"

	.align 2
Cry_Huntail::
	.incbin "sound/direct_sound_samples/cry_huntail.bin"

	.align 2
Cry_Gorebyss::
	.incbin "sound/direct_sound_samples/cry_gorebyss.bin"

	.align 2
Cry_Lileep::
	.incbin "sound/direct_sound_samples/cry_lileep.bin"

	.align 2
Cry_Cradily::
	.incbin "sound/direct_sound_samples/cry_cradily.bin"

	.align 2
Cry_Anorith::
	.incbin "sound/direct_sound_samples/cry_anorith.bin"

	.align 2
Cry_Armaldo::
	.incbin "sound/direct_sound_samples/cry_armaldo.bin"

	.align 2
Cry_Beldum::
	.incbin "sound/direct_sound_samples/cry_beldum.bin"

	.align 2
Cry_Metang::
	.incbin "sound/direct_sound_samples/cry_metang.bin"

	.align 2
Cry_Metagross::
	.incbin "sound/direct_sound_samples/cry_metagross.bin"

	.align 2
Cry_Bagon::
	.incbin "sound/direct_sound_samples/cry_bagon.bin"

	.align 2
Cry_Shelgon::
	.incbin "sound/direct_sound_samples/cry_shelgon.bin"

	.align 2
Cry_Regirock::
	.incbin "sound/direct_sound_samples/cry_regirock.bin"

	.align 2
Cry_Regice::
	.incbin "sound/direct_sound_samples/cry_regice.bin"

	.align 2
Cry_Registeel::
	.incbin "sound/direct_sound_samples/cry_registeel.bin"

	.align 2
Cry_Castform::
	.incbin "sound/direct_sound_samples/cry_castform.bin"

	.align 2
Cry_Volbeat::
	.incbin "sound/direct_sound_samples/cry_volbeat.bin"

	.align 2
Cry_Illumise::
	.incbin "sound/direct_sound_samples/cry_illumise.bin"

	.align 2
Cry_Poochyena::
	.incbin "sound/direct_sound_samples/cry_poochyena.bin"

	.align 2
Cry_Mightyena::
	.incbin "sound/direct_sound_samples/cry_mightyena.bin"

	.align 2
Cry_Dusclops::
	.incbin "sound/direct_sound_samples/cry_dusclops.bin"

	.align 2
Cry_Sableye::
	.incbin "sound/direct_sound_samples/cry_sableye.bin"

	.align 2
Cry_Mawile::
	.incbin "sound/direct_sound_samples/cry_mawile.bin"

	.align 2
Cry_Aron::
	.incbin "sound/direct_sound_samples/cry_aron.bin"

	.align 2
Cry_Lairon::
	.incbin "sound/direct_sound_samples/cry_lairon.bin"

	.align 2
Cry_Aggron::
	.incbin "sound/direct_sound_samples/cry_aggron.bin"

	.align 2
Cry_Relicanth::
	.incbin "sound/direct_sound_samples/cry_relicanth.bin"

	.align 2
Cry_Luvdisc::
	.incbin "sound/direct_sound_samples/cry_luvdisc.bin"

	.align 2
Cry_Groudon::
	.incbin "sound/direct_sound_samples/cry_groudon.bin"

	.align 2
Cry_Kyogre::
	.incbin "sound/direct_sound_samples/cry_kyogre.bin"

	.align 2
Cry_Rayquaza::
	.incbin "sound/direct_sound_samples/cry_rayquaza.bin"

	.align 2
Cry_Salamence::
	.incbin "sound/direct_sound_samples/cry_salamence.bin"

	.align 2
Cry_Breloom::
	.incbin "sound/direct_sound_samples/cry_breloom.bin"

	.align 2
Cry_Shroomish::
	.incbin "sound/direct_sound_samples/cry_shroomish.bin"

	.align 2
Cry_Linoone::
	.incbin "sound/direct_sound_samples/cry_linoone.bin"

	.align 2
Cry_Tropius::
	.incbin "sound/direct_sound_samples/cry_tropius.bin"

	.align 2
Cry_Wailmer::
	.incbin "sound/direct_sound_samples/cry_wailmer.bin"

	.align 2
Cry_Zigzagoon::
	.incbin "sound/direct_sound_samples/cry_zigzagoon.bin"

	.align 2
Cry_Exploud::
	.incbin "sound/direct_sound_samples/cry_exploud.bin"

	.align 2
Cry_Loudred::
	.incbin "sound/direct_sound_samples/cry_loudred.bin"

	.align 2
Cry_Wailord::
	.incbin "sound/direct_sound_samples/cry_wailord.bin"

	.align 2
Cry_Whismur::
	.incbin "sound/direct_sound_samples/cry_whismur.bin"

	.align 2
Cry_Snorunt::
	.incbin "sound/direct_sound_samples/cry_snorunt.bin"

	.align 2
Cry_Latios::
	.incbin "sound/direct_sound_samples/cry_latios.bin"

	.align 2
Cry_Jirachi::
	.incbin "sound/direct_sound_samples/cry_jirachi.bin"

	.align 2
Cry_Deoxys::
	.incbin "sound/direct_sound_samples/cry_deoxys.bin"

	.align 2
Cry_Chimecho::
	.incbin "sound/direct_sound_samples/cry_chimecho.bin"

	.align 2
Cry_Turtwig::
	.incbin "sound/direct_sound_samples/cry_not_turtwig.bin"

Cry_Grotle::
	.incbin "sound/direct_sound_samples/cry_not_grotle.bin"

	.align 2
Cry_Torterra::
	.incbin "sound/direct_sound_samples/cry_not_torterra.bin"

	.align 2
Cry_Chimchar::
	.incbin "sound/direct_sound_samples/cry_not_chimchar.bin"

	.align 2
Cry_Monferno::
	.incbin "sound/direct_sound_samples/cry_not_monferno.bin"

	.align 2
Cry_Infernape::
	.incbin "sound/direct_sound_samples/cry_not_infernape.bin"

	.align 2
Cry_Piplup::
	.incbin "sound/direct_sound_samples/cry_not_piplup.bin"

	.align 2
Cry_Prinplup::
	.incbin "sound/direct_sound_samples/cry_not_prinplup.bin"

	.align 2
Cry_Empoleon::
	.incbin "sound/direct_sound_samples/cry_not_empoleon.bin"

	.align 2
Cry_Starly::
	.incbin "sound/direct_sound_samples/cry_not_starly.bin"

	.align 2
Cry_Staravia::
	.incbin "sound/direct_sound_samples/cry_not_staravia.bin"

	.align 2
Cry_Staraptor::
	.incbin "sound/direct_sound_samples/cry_not_staraptor.bin"

	.align 2
Cry_Bidoof::
	.incbin "sound/direct_sound_samples/cry_not_bidoof.bin"

	.align 2
Cry_Bibarel::
	.incbin "sound/direct_sound_samples/cry_not_bibarel.bin"

	.align 2
Cry_Kricketot::
	.incbin "sound/direct_sound_samples/cry_not_kricketot.bin"

	.align 2
Cry_Kricketune::
	.incbin "sound/direct_sound_samples/cry_not_kricketune.bin"

	.align 2
Cry_Shinx::
	.incbin "sound/direct_sound_samples/cry_not_shinx.bin"

	.align 2
Cry_Luxio::
	.incbin "sound/direct_sound_samples/cry_not_luxio.bin"

	.align 2
Cry_Luxray::
	.incbin "sound/direct_sound_samples/cry_not_luxray.bin"

	.align 2
Cry_Budew::
	.incbin "sound/direct_sound_samples/cry_not_budew.bin"

	.align 2
Cry_Roserade::
	.incbin "sound/direct_sound_samples/cry_not_roserade.bin"

	.align 2
Cry_Cranidos::
	.incbin "sound/direct_sound_samples/cry_not_cranidos.bin"

	.align 2
Cry_Rampardos::
	.incbin "sound/direct_sound_samples/cry_not_rampardos.bin"

	.align 2
Cry_Shieldon::
	.incbin "sound/direct_sound_samples/cry_not_shieldon.bin"

	.align 2
Cry_Bastiodon::
	.incbin "sound/direct_sound_samples/cry_not_bastiodon.bin"

	.align 2
Cry_Burmy::
	.incbin "sound/direct_sound_samples/cry_not_burmy.bin"

	.align 2
Cry_Wormadam::
	.incbin "sound/direct_sound_samples/cry_not_wormadam.bin"

	.align 2
Cry_Mothim::
	.incbin "sound/direct_sound_samples/cry_not_mothim.bin"

	.align 2
Cry_Combee::
	.incbin "sound/direct_sound_samples/cry_not_combee.bin"

	.align 2
Cry_Vespiquen::
	.incbin "sound/direct_sound_samples/cry_not_vespiquen.bin"

	.align 2
Cry_Pachirisu::
	.incbin "sound/direct_sound_samples/cry_not_pachirisu.bin"

	.align 2
Cry_Buizel::
	.incbin "sound/direct_sound_samples/cry_not_buizel.bin"

	.align 2
Cry_Floatzel::
	.incbin "sound/direct_sound_samples/cry_not_floatzel.bin"

	.align 2
Cry_Cherubi::
	.incbin "sound/direct_sound_samples/cry_not_cherubi.bin"

	.align 2
Cry_Cherrim::
	.incbin "sound/direct_sound_samples/cry_not_cherrim.bin"

	.align 2
Cry_Shellos::
	.incbin "sound/direct_sound_samples/cry_not_shellos.bin"

	.align 2
Cry_Gastrodon::
	.incbin "sound/direct_sound_samples/cry_not_gastrodon.bin"

	.align 2
Cry_Ambipom::
	.incbin "sound/direct_sound_samples/cry_not_ambipom.bin"

	.align 2
Cry_Drifloon::
	.incbin "sound/direct_sound_samples/cry_not_drifloon.bin"

	.align 2
Cry_Drifblim::
	.incbin "sound/direct_sound_samples/cry_not_drifblim.bin"

	.align 2
Cry_Buneary::
	.incbin "sound/direct_sound_samples/cry_not_buneary.bin"

	.align 2
Cry_Lopunny::
	.incbin "sound/direct_sound_samples/cry_not_lopunny.bin"

	.align 2
Cry_Mismagius::
	.incbin "sound/direct_sound_samples/cry_not_mismagius.bin"

	.align 2
Cry_Honchkrow::
	.incbin "sound/direct_sound_samples/cry_not_honchkrow.bin"

	.align 2
Cry_Glameow::
	.incbin "sound/direct_sound_samples/cry_not_glameow.bin"

	.align 2
Cry_Purugly::
	.incbin "sound/direct_sound_samples/cry_not_purugly.bin"

	.align 2
Cry_Chingling::
	.incbin "sound/direct_sound_samples/cry_not_chingling.bin"

	.align 2
Cry_Stunky::
	.incbin "sound/direct_sound_samples/cry_not_stunky.bin"

	.align 2
Cry_Skuntank::
	.incbin "sound/direct_sound_samples/cry_not_skuntank.bin"

	.align 2
Cry_Bronzor::
	.incbin "sound/direct_sound_samples/cry_not_bronzor.bin"

	.align 2
Cry_Bronzong::
	.incbin "sound/direct_sound_samples/cry_not_bronzong.bin"

	.align 2
Cry_Bonsly::
	.incbin "sound/direct_sound_samples/cry_not_bonsly.bin"

	.align 2
Cry_Mimejr::
	.incbin "sound/direct_sound_samples/cry_not_mimejr.bin"

	.align 2
Cry_Happiny::
	.incbin "sound/direct_sound_samples/cry_not_happiny.bin"

	.align 2
Cry_Chatot::
	.incbin "sound/direct_sound_samples/cry_not_chatot.bin"

	.align 2
Cry_Spiritomb::
	.incbin "sound/direct_sound_samples/cry_not_spiritomb.bin"

	.align 2
Cry_Gible::
	.incbin "sound/direct_sound_samples/cry_not_gible.bin"

	.align 2
Cry_Gabite::
	.incbin "sound/direct_sound_samples/cry_not_gabite.bin"

	.align 2
Cry_Garchomp::
	.incbin "sound/direct_sound_samples/cry_not_garchomp.bin"

	.align 2
Cry_Munchlax::
	.incbin "sound/direct_sound_samples/cry_not_munchlax.bin"

	.align 2
Cry_Riolu::
	.incbin "sound/direct_sound_samples/cry_not_riolu.bin"

	.align 2
Cry_Lucario::
	.incbin "sound/direct_sound_samples/cry_not_lucario.bin"

	.align 2
Cry_Hippopotas::
	.incbin "sound/direct_sound_samples/cry_not_hippopotas.bin"

	.align 2
Cry_Hippowdon::
	.incbin "sound/direct_sound_samples/cry_not_hippowdon.bin"

	.align 2
Cry_Skorupi::
	.incbin "sound/direct_sound_samples/cry_not_skorupi.bin"

	.align 2
Cry_Drapion::
	.incbin "sound/direct_sound_samples/cry_not_drapion.bin"

	.align 2
Cry_Croagunk::
	.incbin "sound/direct_sound_samples/cry_not_croagunk.bin"

	.align 2
Cry_Toxicroak::
	.incbin "sound/direct_sound_samples/cry_not_toxicroak.bin"

	.align 2
Cry_Carnivine::
	.incbin "sound/direct_sound_samples/cry_not_carnivine.bin"

	.align 2
Cry_Finneon::
	.incbin "sound/direct_sound_samples/cry_not_finneon.bin"

	.align 2
Cry_Lumineon::
	.incbin "sound/direct_sound_samples/cry_not_lumineon.bin"

	.align 2
Cry_Mantyke::
	.incbin "sound/direct_sound_samples/cry_not_mantyke.bin"

	.align 2
Cry_Snover::
	.incbin "sound/direct_sound_samples/cry_not_snover.bin"

	.align 2
Cry_Abomasnow::
	.incbin "sound/direct_sound_samples/cry_not_abomasnow.bin"

	.align 2
Cry_Weavile::
	.incbin "sound/direct_sound_samples/cry_not_weavile.bin"

	.align 2
Cry_Magnezone::
	.incbin "sound/direct_sound_samples/cry_not_magnezone.bin"

	.align 2
Cry_Lickilicky::
	.incbin "sound/direct_sound_samples/cry_not_lickilicky.bin"

	.align 2
Cry_Rhyperior::
	.incbin "sound/direct_sound_samples/cry_not_rhyperior.bin"

	.align 2
Cry_Tangrowth::
	.incbin "sound/direct_sound_samples/cry_not_tangrowth.bin"

	.align 2
Cry_Electivire::
	.incbin "sound/direct_sound_samples/cry_not_electivire.bin"

	.align 2
Cry_Magmortar::
	.incbin "sound/direct_sound_samples/cry_not_magmortar.bin"

	.align 2
Cry_Togekiss::
	.incbin "sound/direct_sound_samples/cry_not_togekiss.bin"

	.align 2
Cry_Yanmega::
	.incbin "sound/direct_sound_samples/cry_not_yanmega.bin"

	.align 2
Cry_Leafeon::
	.incbin "sound/direct_sound_samples/cry_not_leafeon.bin"

	.align 2
Cry_Glaceon::
	.incbin "sound/direct_sound_samples/cry_not_glaceon.bin"

	.align 2
Cry_Gliscor::
	.incbin "sound/direct_sound_samples/cry_not_gliscor.bin"

	.align 2
Cry_Mamoswine::
	.incbin "sound/direct_sound_samples/cry_not_mamoswine.bin"

	.align 2
Cry_PorygonZ::
	.incbin "sound/direct_sound_samples/cry_not_porygonZ.bin"

	.align 2
Cry_Gallade::
	.incbin "sound/direct_sound_samples/cry_not_gallade.bin"

	.align 2
Cry_Probopass::
	.incbin "sound/direct_sound_samples/cry_not_probopass.bin"

	.align 2
Cry_Dusknoir::
	.incbin "sound/direct_sound_samples/cry_not_dusknoir.bin"

	.align 2
Cry_Froslass::
	.incbin "sound/direct_sound_samples/cry_not_froslass.bin"

	.align 2
Cry_Rotom::
	.incbin "sound/direct_sound_samples/cry_not_rotom.bin"

	.align 2
Cry_Uxie::
	.incbin "sound/direct_sound_samples/cry_not_uxie.bin"

	.align 2
Cry_Mesprit::
	.incbin "sound/direct_sound_samples/cry_not_mesprit.bin"

	.align 2
Cry_Azelf::
	.incbin "sound/direct_sound_samples/cry_not_azelf.bin"

	.align 2
Cry_Dialga::
	.incbin "sound/direct_sound_samples/cry_not_dialga.bin"

	.align 2
Cry_Palkia::
	.incbin "sound/direct_sound_samples/cry_not_palkia.bin"

	.align 2
Cry_Heatran::
	.incbin "sound/direct_sound_samples/cry_not_heatran.bin"

	.align 2
Cry_Regigigas::
	.incbin "sound/direct_sound_samples/cry_not_regigigas.bin"

	.align 2
Cry_Giratina::
	.incbin "sound/direct_sound_samples/cry_not_giratina.bin"

	.align 2
Cry_Cresselia::
	.incbin "sound/direct_sound_samples/cry_not_cresselia.bin"

	.align 2
Cry_Phione::
	.incbin "sound/direct_sound_samples/cry_not_phione.bin"

	.align 2
Cry_Manaphy::
	.incbin "sound/direct_sound_samples/cry_not_manaphy.bin"

	.align 2
Cry_Darkrai::
	.incbin "sound/direct_sound_samples/cry_not_darkrai.bin"

	.align 2
Cry_Shaymin::
	.incbin "sound/direct_sound_samples/cry_not_shaymin.bin"

	.align 2
Cry_Arceus::
	.incbin "sound/direct_sound_samples/cry_not_arceus.bin"

	.align 2
Cry_Victini::
	.incbin "sound/direct_sound_samples/cry_not_victini.bin"

	.align 2
Cry_Snivy::
	.incbin "sound/direct_sound_samples/cry_not_snivy.bin"

	.align 2
Cry_Servine::
	.incbin "sound/direct_sound_samples/cry_not_servine.bin"

	.align 2
Cry_Serperior::
	.incbin "sound/direct_sound_samples/cry_not_serperior.bin"

	.align 2
Cry_Tepig::
	.incbin "sound/direct_sound_samples/cry_not_tepig.bin"

	.align 2
Cry_Pignite::
	.incbin "sound/direct_sound_samples/cry_not_pignite.bin"

	.align 2
Cry_Emboar::
	.incbin "sound/direct_sound_samples/cry_not_emboar.bin"

	.align 2
Cry_Oshawott::
	.incbin "sound/direct_sound_samples/cry_not_oshawott.bin"

	.align 2
Cry_Dewott::
	.incbin "sound/direct_sound_samples/cry_not_dewott.bin"

	.align 2
Cry_Samurott::
	.incbin "sound/direct_sound_samples/cry_not_samurott.bin"

	.align 2
Cry_Patrat::
	.incbin "sound/direct_sound_samples/cry_not_patrat.bin"

	.align 2
Cry_Watchog::
	.incbin "sound/direct_sound_samples/cry_not_watchog.bin"

	.align 2
Cry_Lillipup::
	.incbin "sound/direct_sound_samples/cry_not_lillipup.bin"

	.align 2
Cry_Herdier::
	.incbin "sound/direct_sound_samples/cry_not_herdier.bin"

	.align 2
Cry_Stoutland::
	.incbin "sound/direct_sound_samples/cry_not_stoutland.bin"

	.align 2
Cry_Purrloin::
	.incbin "sound/direct_sound_samples/cry_not_purrloin.bin"

	.align 2
Cry_Liepard::
	.incbin "sound/direct_sound_samples/cry_not_liepard.bin"

	.align 2
Cry_Pansage::
	.incbin "sound/direct_sound_samples/cry_not_pansage.bin"

	.align 2
Cry_Simisage::
	.incbin "sound/direct_sound_samples/cry_not_simisage.bin"

	.align 2
Cry_Pansear::
	.incbin "sound/direct_sound_samples/cry_not_pansear.bin"

	.align 2
Cry_Simisear::
	.incbin "sound/direct_sound_samples/cry_not_simisear.bin"

	.align 2
Cry_Panpour::
	.incbin "sound/direct_sound_samples/cry_not_panpour.bin"

	.align 2
Cry_Simipour::
	.incbin "sound/direct_sound_samples/cry_not_simipour.bin"

	.align 2
Cry_Munna::
	.incbin "sound/direct_sound_samples/cry_not_munna.bin"

	.align 2
Cry_Musharna::
	.incbin "sound/direct_sound_samples/cry_not_musharna.bin"

	.align 2
Cry_Pidove::
	.incbin "sound/direct_sound_samples/cry_not_pidove.bin"

	.align 2
Cry_Tranquill::
	.incbin "sound/direct_sound_samples/cry_not_tranquill.bin"

	.align 2
Cry_Unfezant::
	.incbin "sound/direct_sound_samples/cry_not_unfezant.bin"

	.align 2
Cry_Blitzle::
	.incbin "sound/direct_sound_samples/cry_not_blitzle.bin"

	.align 2
Cry_Zebstrika::
	.incbin "sound/direct_sound_samples/cry_not_zebstrika.bin"

	.align 2
Cry_Roggenrola::
	.incbin "sound/direct_sound_samples/cry_not_roggenrola.bin"

	.align 2
Cry_Boldore::
	.incbin "sound/direct_sound_samples/cry_not_boldore.bin"

	.align 2
Cry_Gigalith::
	.incbin "sound/direct_sound_samples/cry_not_gigalith.bin"

	.align 2
Cry_Woobat::
	.incbin "sound/direct_sound_samples/cry_not_woobat.bin"

	.align 2
Cry_Swoobat::
	.incbin "sound/direct_sound_samples/cry_not_swoobat.bin"

	.align 2
Cry_Drilbur::
	.incbin "sound/direct_sound_samples/cry_not_drilbur.bin"

	.align 2
Cry_Excadrill::
	.incbin "sound/direct_sound_samples/cry_not_excadrill.bin"

	.align 2
Cry_Audino::
	.incbin "sound/direct_sound_samples/cry_not_audino.bin"

	.align 2
Cry_Timburr::
	.incbin "sound/direct_sound_samples/cry_not_timburr.bin"

	.align 2
Cry_Gurdurr::
	.incbin "sound/direct_sound_samples/cry_not_gurdurr.bin"

	.align 2
Cry_Conkeldurr::
	.incbin "sound/direct_sound_samples/cry_not_conkeldurr.bin"

	.align 2
Cry_Tympole::
	.incbin "sound/direct_sound_samples/cry_not_tympole.bin"

	.align 2
Cry_Palpitoad::
	.incbin "sound/direct_sound_samples/cry_not_palpitoad.bin"

	.align 2
Cry_Seismitoad::
	.incbin "sound/direct_sound_samples/cry_not_seismitoad.bin"

	.align 2
Cry_Throh::
	.incbin "sound/direct_sound_samples/cry_not_throh.bin"

	.align 2
Cry_Sawk::
	.incbin "sound/direct_sound_samples/cry_not_sawk.bin"

	.align 2
Cry_Sewaddle::
	.incbin "sound/direct_sound_samples/cry_not_sewaddle.bin"

	.align 2
Cry_Swadloon::
	.incbin "sound/direct_sound_samples/cry_not_swadloon.bin"

	.align 2
Cry_Leavanny::
	.incbin "sound/direct_sound_samples/cry_not_leavanny.bin"

	.align 2
Cry_Venipede::
	.incbin "sound/direct_sound_samples/cry_not_venipede.bin"

	.align 2
Cry_Whirlipede::
	.incbin "sound/direct_sound_samples/cry_not_whirlipede.bin"

	.align 2
Cry_Scolipede::
	.incbin "sound/direct_sound_samples/cry_not_scolipede.bin"

	.align 2
Cry_Cottonee::
	.incbin "sound/direct_sound_samples/cry_not_cottonee.bin"

	.align 2
Cry_Whimsicott::
	.incbin "sound/direct_sound_samples/cry_not_whimsicott.bin"

	.align 2
Cry_Petilil::
	.incbin "sound/direct_sound_samples/cry_not_petilil.bin"

	.align 2
Cry_Lilligant::
	.incbin "sound/direct_sound_samples/cry_not_lilligant.bin"

	.align 2
Cry_Basculin::
	.incbin "sound/direct_sound_samples/cry_not_basculin.bin"

	.align 2
Cry_Sandile::
	.incbin "sound/direct_sound_samples/cry_not_sandile.bin"

	.align 2
Cry_Krokorok::
	.incbin "sound/direct_sound_samples/cry_not_krokorok.bin"

	.align 2
Cry_Krookodile::
	.incbin "sound/direct_sound_samples/cry_not_krookodile.bin"

	.align 2
Cry_Darumaka::
	.incbin "sound/direct_sound_samples/cry_not_darumaka.bin"

	.align 2
Cry_Darmanitan::
	.incbin "sound/direct_sound_samples/cry_not_darmanitan.bin"

	.align 2
Cry_Maractus::
	.incbin "sound/direct_sound_samples/cry_not_maractus.bin"

	.align 2
Cry_Dwebble::
	.incbin "sound/direct_sound_samples/cry_not_dwebble.bin"

	.align 2
Cry_Crustle::
	.incbin "sound/direct_sound_samples/cry_not_crustle.bin"

	.align 2
Cry_Scraggy::
	.incbin "sound/direct_sound_samples/cry_not_scraggy.bin"

	.align 2
Cry_Scrafty::
	.incbin "sound/direct_sound_samples/cry_not_scrafty.bin"

	.align 2
Cry_Sigilyph::
	.incbin "sound/direct_sound_samples/cry_not_sigilyph.bin"

	.align 2
Cry_Yamask::
	.incbin "sound/direct_sound_samples/cry_not_yamask.bin"

	.align 2
Cry_Cofagrigus::
	.incbin "sound/direct_sound_samples/cry_not_cofagrigus.bin"

	.align 2
Cry_Tirtouga::
	.incbin "sound/direct_sound_samples/cry_not_tirtouga.bin"

	.align 2
Cry_Carracosta::
	.incbin "sound/direct_sound_samples/cry_not_carracosta.bin"

	.align 2
Cry_Archen::
	.incbin "sound/direct_sound_samples/cry_not_archen.bin"

	.align 2
Cry_Archeops::
	.incbin "sound/direct_sound_samples/cry_not_archeops.bin"

	.align 2
Cry_Trubbish::
	.incbin "sound/direct_sound_samples/cry_not_trubbish.bin"

	.align 2
Cry_Garbodor::
	.incbin "sound/direct_sound_samples/cry_not_garbodor.bin"

	.align 2
Cry_Zorua::
	.incbin "sound/direct_sound_samples/cry_not_zorua.bin"

	.align 2
Cry_Zoroark::
	.incbin "sound/direct_sound_samples/cry_not_zoroark.bin"

	.align 2
Cry_Minccino::
	.incbin "sound/direct_sound_samples/cry_not_minccino.bin"

	.align 2
Cry_Cinccino::
	.incbin "sound/direct_sound_samples/cry_not_cinccino.bin"

	.align 2
Cry_Gothita::
	.incbin "sound/direct_sound_samples/cry_not_gothita.bin"

	.align 2
Cry_Gothorita::
	.incbin "sound/direct_sound_samples/cry_not_gothorita.bin"

	.align 2
Cry_Gothitelle::
	.incbin "sound/direct_sound_samples/cry_not_gothitelle.bin"

	.align 2
Cry_Solosis::
	.incbin "sound/direct_sound_samples/cry_not_solosis.bin"

	.align 2
Cry_Duosion::
	.incbin "sound/direct_sound_samples/cry_not_duosion.bin"

	.align 2
Cry_Reuniclus::
	.incbin "sound/direct_sound_samples/cry_not_reuniclus.bin"

	.align 2
Cry_Ducklett::
	.incbin "sound/direct_sound_samples/cry_not_ducklett.bin"

	.align 2
Cry_Swanna::
	.incbin "sound/direct_sound_samples/cry_not_swanna.bin"

	.align 2
Cry_Vanillite::
	.incbin "sound/direct_sound_samples/cry_not_vanillite.bin"

	.align 2
Cry_Vanillish::
	.incbin "sound/direct_sound_samples/cry_not_vanillish.bin"

	.align 2
Cry_Vanilluxe::
	.incbin "sound/direct_sound_samples/cry_not_vanilluxe.bin"

	.align 2
Cry_Deerling::
	.incbin "sound/direct_sound_samples/cry_not_deerling.bin"

	.align 2
Cry_Sawsbuck::
	.incbin "sound/direct_sound_samples/cry_not_sawsbuck.bin"

	.align 2
Cry_Emolga::
	.incbin "sound/direct_sound_samples/cry_not_emolga.bin"

	.align 2
Cry_Karrablast::
	.incbin "sound/direct_sound_samples/cry_not_karrablast.bin"

	.align 2
Cry_Escavalier::
	.incbin "sound/direct_sound_samples/cry_not_escavalier.bin"

	.align 2
Cry_Foongus::
	.incbin "sound/direct_sound_samples/cry_not_foongus.bin"

	.align 2
Cry_Amoonguss::
	.incbin "sound/direct_sound_samples/cry_not_amoonguss.bin"

	.align 2
Cry_Frillish::
	.incbin "sound/direct_sound_samples/cry_not_frillish.bin"

	.align 2
Cry_Jellicent::
	.incbin "sound/direct_sound_samples/cry_not_jellicent.bin"

	.align 2
Cry_Alomomola::
	.incbin "sound/direct_sound_samples/cry_not_alomomola.bin"

	.align 2
Cry_Joltik::
	.incbin "sound/direct_sound_samples/cry_not_joltik.bin"

	.align 2
Cry_Galvantula::
	.incbin "sound/direct_sound_samples/cry_not_galvantula.bin"

	.align 2
Cry_Ferroseed::
	.incbin "sound/direct_sound_samples/cry_not_ferroseed.bin"

	.align 2
Cry_Ferrothorn::
	.incbin "sound/direct_sound_samples/cry_not_ferrothorn.bin"

	.align 2
Cry_Klink::
	.incbin "sound/direct_sound_samples/cry_not_klink.bin"

	.align 2
Cry_Klang::
	.incbin "sound/direct_sound_samples/cry_not_klang.bin"

	.align 2
Cry_Klinklang::
	.incbin "sound/direct_sound_samples/cry_not_klinklang.bin"

	.align 2
Cry_Tynamo::
	.incbin "sound/direct_sound_samples/cry_not_tynamo.bin"

	.align 2
Cry_Eelektrik::
	.incbin "sound/direct_sound_samples/cry_not_eelektrik.bin"

	.align 2
Cry_Eelektross::
	.incbin "sound/direct_sound_samples/cry_not_eelektross.bin"

	.align 2
Cry_Elgyem::
	.incbin "sound/direct_sound_samples/cry_not_elgyem.bin"

	.align 2
Cry_Beheeyem::
	.incbin "sound/direct_sound_samples/cry_not_beheeyem.bin"

	.align 2
Cry_Litwick::
	.incbin "sound/direct_sound_samples/cry_not_litwick.bin"

	.align 2
Cry_Lampent::
	.incbin "sound/direct_sound_samples/cry_not_lampent.bin"

	.align 2
Cry_Chandelure::
	.incbin "sound/direct_sound_samples/cry_not_chandelure.bin"

	.align 2
Cry_Axew::
	.incbin "sound/direct_sound_samples/cry_not_axew.bin"

	.align 2
Cry_Fraxure::
	.incbin "sound/direct_sound_samples/cry_not_fraxure.bin"

	.align 2
Cry_Haxorus::
	.incbin "sound/direct_sound_samples/cry_not_haxorus.bin"

	.align 2
Cry_Cubchoo::
	.incbin "sound/direct_sound_samples/cry_not_cubchoo.bin"

	.align 2
Cry_Beartic::
	.incbin "sound/direct_sound_samples/cry_not_beartic.bin"

	.align 2
Cry_Cryogonal::
	.incbin "sound/direct_sound_samples/cry_not_cryogonal.bin"

	.align 2
Cry_Shelmet::
	.incbin "sound/direct_sound_samples/cry_not_shelmet.bin"

	.align 2
Cry_Accelgor::
	.incbin "sound/direct_sound_samples/cry_not_accelgor.bin"

	.align 2
Cry_Stunfisk::
	.incbin "sound/direct_sound_samples/cry_not_stunfisk.bin"

	.align 2
Cry_Mienfoo::
	.incbin "sound/direct_sound_samples/cry_not_mienfoo.bin"

	.align 2
Cry_Mienshao::
	.incbin "sound/direct_sound_samples/cry_not_mienshao.bin"

	.align 2
Cry_Druddigon::
	.incbin "sound/direct_sound_samples/cry_not_druddigon.bin"

	.align 2
Cry_Golett::
	.incbin "sound/direct_sound_samples/cry_not_golett.bin"

	.align 2
Cry_Golurk::
	.incbin "sound/direct_sound_samples/cry_not_golurk.bin"

	.align 2
Cry_Pawniard::
	.incbin "sound/direct_sound_samples/cry_not_pawniard.bin"

	.align 2
Cry_Bisharp::
	.incbin "sound/direct_sound_samples/cry_not_bisharp.bin"

	.align 2
Cry_Bouffalant::
	.incbin "sound/direct_sound_samples/cry_not_bouffalant.bin"

	.align 2
Cry_Rufflet::
	.incbin "sound/direct_sound_samples/cry_not_rufflet.bin"

	.align 2
Cry_Braviary::
	.incbin "sound/direct_sound_samples/cry_not_braviary.bin"

	.align 2
Cry_Vullaby::
	.incbin "sound/direct_sound_samples/cry_not_vullaby.bin"

	.align 2
Cry_Mandibuzz::
	.incbin "sound/direct_sound_samples/cry_not_mandibuzz.bin"

	.align 2
Cry_Heatmor::
	.incbin "sound/direct_sound_samples/cry_not_heatmor.bin"

	.align 2
Cry_Durant::
	.incbin "sound/direct_sound_samples/cry_not_durant.bin"

	.align 2
Cry_Deino::
	.incbin "sound/direct_sound_samples/cry_not_deino.bin"

	.align 2
Cry_Zweilous::
	.incbin "sound/direct_sound_samples/cry_not_zweilous.bin"

	.align 2
Cry_Hydreigon::
	.incbin "sound/direct_sound_samples/cry_not_hydreigon.bin"

	.align 2
Cry_Larvesta::
	.incbin "sound/direct_sound_samples/cry_not_larvesta.bin"

	.align 2
Cry_Volcarona::
	.incbin "sound/direct_sound_samples/cry_not_volcarona.bin"

	.align 2
Cry_Cobalion::
	.incbin "sound/direct_sound_samples/cry_not_cobalion.bin"

	.align 2
Cry_Terrakion::
	.incbin "sound/direct_sound_samples/cry_not_terrakion.bin"

	.align 2
Cry_Virizion::
	.incbin "sound/direct_sound_samples/cry_not_virizion.bin"

	.align 2
Cry_Tornadus::
	.incbin "sound/direct_sound_samples/cry_not_tornadus.bin"

	.align 2
Cry_Thundurus::
	.incbin "sound/direct_sound_samples/cry_not_thundurus.bin"

	.align 2
Cry_Reshiram::
	.incbin "sound/direct_sound_samples/cry_not_reshiram.bin"

	.align 2
Cry_Zekrom::
	.incbin "sound/direct_sound_samples/cry_not_zekrom.bin"

	.align 2
Cry_Landorus::
	.incbin "sound/direct_sound_samples/cry_not_landorus.bin"

	.align 2
Cry_Kyurem::
	.incbin "sound/direct_sound_samples/cry_not_kyurem.bin"

	.align 2
Cry_Keldeo::
	.incbin "sound/direct_sound_samples/cry_not_keldeo.bin"

	.align 2
Cry_Meloetta::
	.incbin "sound/direct_sound_samples/cry_not_meloetta.bin"

	.align 2
Cry_Genesect::
	.incbin "sound/direct_sound_samples/cry_not_genesect.bin"

	.align 2
Cry_Sylveon::
	.incbin "sound/direct_sound_samples/cry_not_sylveon.bin"

	.align 2
Cry_Missingno::
	.incbin "sound/direct_sound_samples/cry_missingno.bin"

	.align 2
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.align 2
DirectSoundWaveData_wave_77::
	.incbin "sound/direct_sound_samples/wave_77.bin"

	.align 2
DirectSoundWaveData_sc88pro_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88pro_nylon_str_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/sd90_special_scream_drive.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion_duplicate::
	.incbin "sound/direct_sound_samples/sc88pro_accordion_duplicate.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_high.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"
