#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

#define SPAWN_SEASHORE_CITY 1
#define SPAWN_GRAVEL_TOWN 2
#define SPAWN_MERSON_CITY 3

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
