#ifndef GUARD_CONSTANTS_LAYOUTS_H
#define GUARD_CONSTANTS_LAYOUTS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/layouts/layouts.json
//

#define LAYOUT_SEASHORE_CITY_PLAYERS_HOUSE_2F 1
#define LAYOUT_SEASHORE_CITY_PLAYERS_HOUSE_1F 2
#define LAYOUT_SEASHORE_CITY 3
#define LAYOUT_SEASHORE_CITY_MURAS_HOUSE 4
#define LAYOUT_ROUTE53 5
#define LAYOUT_GRAVEL_TOWN 6
#define LAYOUT_GRAVEL_TOWN_HOUSE 7
#define LAYOUT_POKE_MART 8
#define LAYOUT_GRAVEL_TOWN_TIMS_LAB 9
#define LAYOUT_MERSON_CAVE_1F 10
#define LAYOUT_MERSON_CAVE_1BF 11
#define LAYOUT_MERSON_CAVE_2BF 12
#define LAYOUT_MERSON_CAVE_OUTDOOR 13
#define LAYOUT_MERSON_CAVE_2F 14
#define LAYOUT_DEBUG_WARP_ZONE 15
#define LAYOUT_DEBUG_PLACEHOLDER 16
#define LAYOUT_ROUTE54 17
#define LAYOUT_MERSON_CITY 18
#define LAYOUT_SOUTH_RIJON_GATE 19
#define LAYOUT_POKE_CENTER 20
#define LAYOUT_MERSON_CITY_HOUSE 21
#define LAYOUT_MERSON_CITY_FAN_CLUB 22
#define LAYOUT_MERSON_CITY_GYM 23

#endif // GUARD_CONSTANTS_LAYOUTS_H
