gOtherText_NewName:: @ 81C574F
    .string "NEW NAME$"

gNameChoice_Green:: @ 81C5758
    .string "GREEN$"

gNameChoice_Red:: @ 81C575E
    .string "RED$"

gNameChoice_Leaf:: @ 81C5762
    .string "LEAF$"

gNameChoice_Fire:: @ 81C5767
    .string "FIRE$"

gNameChoice_Gary:: @ 81C576C
    .string "GARY$"

gNameChoice_Kaz:: @ 81C5771
    .string "KAZ$"

gNameChoice_Toru:: @ 81C5775
    .string "TORU$"

gNameChoice_Ash:: @ 81C577A
    .string "ASH$"

gNameChoice_Kene:: @ 81C577E
    .string "KENE$"

gNameChoice_Geki:: @ 81C5783
    .string "GEKI$"

gNameChoice_Jak:: @ 81C5788
    .string "JAK$"

gNameChoice_Janne:: @ 81C578C
    .string "JANNE$"

gNameChoice_Jonn:: @ 81C5792
    .string "JONN$"

gNameChoice_Kamon:: @ 81C5797
    .string "KAMON$"

gNameChoice_Karl:: @ 81C579D
    .string "KARL$"

gNameChoice_Taylor:: @ 81C57A2
    .string "TAYLOR$"

gNameChoice_Oscar:: @ 81C57A9
    .string "OSCAR$"

gNameChoice_Hiro:: @ 81C57AF
    .string "HIRO$"

gNameChoice_Max:: @ 81C57B4
    .string "MAX$"

gNameChoice_Jon:: @ 81C57B8
    .string "JON$"

gNameChoice_Ralph:: @ 81C57BC
    .string "RALPH$"

gNameChoice_Kay:: @ 81C57C2
    .string "KAY$"

gNameChoice_Tosh:: @ 81C57C6
    .string "TOSH$"

gNameChoice_Roak:: @ 81C57CB
    .string "ROAK$"

gNameChoice_Omi:: @ 81C57D0
    .string "OMI$"

gNameChoice_Jodi:: @ 81C57D4
    .string "JODI$"

gNameChoice_Amanda:: @ 81C57D9
    .string "AMANDA$"

gNameChoice_Hillary:: @ 81C57E0
    .string "HILLARY$"

gNameChoice_Makey:: @ 81C57E8
    .string "MAKEY$"

gNameChoice_Michi:: @ 81C57EE
    .string "MICHI$"

gNameChoice_Paula:: @ 81C57F4
    .string "PAULA$"

gNameChoice_June:: @ 81C57FA
    .string "JUNE$"

gNameChoice_Cassie:: @ 81C57FF
    .string "CASSIE$"

gNameChoice_Rey:: @ 81C5806
    .string "REY$"

gNameChoice_Seda:: @ 81C580A
    .string "SEDA$"

gNameChoice_Kiko:: @ 81C580F
    .string "KIKO$"

gNameChoice_Mina:: @ 81C5814
    .string "MINA$"

gNameChoice_Norie:: @ 81C5819
    .string "NORIE$"

gNameChoice_Sai:: @ 81C581F
    .string "SAI$"

gNameChoice_Momo:: @ 81C5823
    .string "MOMO$"

gNameChoice_Suzi:: @ 81C5828
    .string "SUZI$"

gNameChoice_Mura::
    .string "Mura$"

gNameChoice_Brown::
    .string "Brown$"

gNameChoice_Adam::
    .string "Adam$"

gNameChoice_Paul::
    .string "Paul$"

gNameChoice_Kyle::
    .string "Kyle$"

gNewGame_HelpDocs1:: @ 81C582D
    .string "The various buttons will be explained in\n"
    .string "the order of their importance.$"

gNewGame_HelpDocs2:: @ 81C5875
    .string "Moves the main character.\n"
    .string "Also used to choose various data\n"
    .string "headings.$"

gNewGame_HelpDocs3:: @ 81C58BA
    .string "Used to confirm a choice, check\n"
    .string "things, chat, and scroll text.$"

gNewGame_HelpDocs4:: @ 81C58F9
    .string "Used to exit, cancel a choice,\n"
    .string "and cancel a mode.$"

gNewGame_HelpDocs5:: @ 81C592B
    .string "Press this button to open the\n"
    .string "MENU.$"

gNewGame_HelpDocs6:: @ 81C594F
    .string "Used to shift items and to use\n"
    .string "a registered item.$"

gNewGame_HelpDocs7:: @ 81C5981
    .string "If you need help playing the\n"
    .string "game, or on how to do things,\n"
    .string "press the L or R Button.$"

gOakText_AskPlayerGender:: @ 81C59D5
    .string "Now tell me. Are you a boy?\n"
    .string "Or are you a girl?$"

gNewGameAdventureIntro1::
    .string "In the world which you are about to\n"
    .string "enter, you will embark on a grand\n"
    .string "adventure with you as the hero.\n"
    .string "\n"
    .string "Speak to people and check things\n"
    .string "wherever you go, be it towns, roads,\n"
    .string "or caves. Gather information and\n"
    .string "hints from every source.$"

gNewGameAdventureIntro2::
    .string "New paths will open to you by helping\n"
    .string "people in need, overcoming challenges,\n"
    .string "and solving mysteries.\n"
    .string "\n"
    .string "At times, you will be challenged by\n"
    .string "others and attacked by wild creatures.\n"
    .string "Be brave and keep pushing on.$"

gNewGameAdventureIntro3::
    .string "Through your adventure, we hope\n"
    .string "that you will interact with all sorts\n"
    .string "of people and achieve personal growth.\n"
    .string "That is our biggest objective.\n"
    .string "\n"
    .string "Press the A Button, and let your\n"
    .string "adventure begin!$"

gOakText_WelcomeToTheWorld:: @ 81C5C78
    .string "H-hello?!\nYou must be new here.\p"
    .string "Welcome to this land, called Rijon!\p"
    .string "My name is Timothy, but you can call\nme Tim.\p"
    .string "I am the island's Pokémon Tutor.\p$"

gOakText_WorldInhabited1:: @ 81C5D06
    .string "$"

gOakText_WorldInhabited2:: @ 81C5D12
    .string "This is a Pokémon. There are a lot of\nthese in the Rijon area.\p$"

gOakText_PetsBattlingStudy:: @ 81C5D4B
    .string "I've done a fair extent of research\non these…\p"
    .string "and it seems that they have special\ncapabilities for fighting, as well as\l"
    .string "being tame household pets.\p$"

gOakText_TellMeALittleAboutYourself:: @ 81C5DBD
    .string "Oh, um, I suppose I'm getting a \nlittle ahead of myself.\p$"

gOakText_AskPlayerName:: @ 81C5DEA
    .string "What's your name, young man?$"

gOakText_FinalizePlayerName:: @ 81C5E13
    .string "Oh, {PLAYER}, right?$"

gOakText_IntroduceRival:: @ 81C5E2E
    .string "This is my grandson.\pHe's been your rival since you both\n"
    .string "were babies.\p…Erm, what was his name now?$"

gOakText_AskRivalName:: @ 81C5E91
    .string "Your rival's name, what was it now?$"

gOakText_ConfirmRivalName:: @ 81C5EB5
    .string "…Er, was it {RIVAL}?$"

gOakText_RememberRivalName:: @ 81C5EC5
    .string "That's right! I remember now!\n"
    .string "His name is {RIVAL}!\p$"

gOakText_LegendAboutToUnfold:: @ 81C5EF4
    .string "{PLAYER}!\nNow that you have met some people…\p"
    .string "…all you need now is to journey the\ntown.\p"
    .string "I think your mother has settled in\nand finished unpacking.\p"
    .string "Your adventure starts here, so come\nsee me sometime tomorrow, after you\lawake.\p"
    .string "See you later!$"
